# Generated by Django 5.1.4 on 2025-01-12 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admission', '0002_admissionform'),
        ('MySchoolApp', '0004_delete_admission_guidelines_delete_school_guidelines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionform',
            name='join_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MySchoolApp.class'),
        ),
    ]
