# Generated by Django 5.1.4 on 2025-01-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admission', '0003_alter_admissionform_join_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionFormPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Offline_pdf', models.FileField(upload_to='')),
            ],
        ),
    ]
