# Generated by Django 5.1.4 on 2025-01-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('event_link', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_location', models.CharField(blank=True, max_length=100, null=True)),
                ('event_day', models.IntegerField(blank=True, null=True)),
                ('event_month', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='News_session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=100)),
                ('short_post_text', models.TextField(max_length=1000)),
                ('news_post_quote', models.TextField(blank=True, null=True)),
                ('news_post_text', models.TextField(blank=True, null=True)),
                ('post_author', models.CharField(blank=True, max_length=50, null=True)),
                ('news_day', models.IntegerField(blank=True, null=True)),
                ('news_month', models.CharField(blank=True, max_length=20, null=True)),
                ('news_image', models.ImageField(upload_to='')),
                ('news_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='notificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('notify_img', models.ImageField(upload_to='')),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
