# Generated by Django 5.1.4 on 2025-01-12 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MySchoolApp', '0003_admission_guidelines_school_guidelines'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admission_Guidelines',
        ),
        migrations.DeleteModel(
            name='School_Guidelines',
        ),
    ]
