# Generated by Django 5.1.4 on 2025-01-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySchoolApp', '0004_delete_admission_guidelines_delete_school_guidelines'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBenner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
