# Generated by Django 5.1.4 on 2025-01-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySchoolApp', '0005_homebenner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homebenner',
            old_name='title',
            new_name='titlefirst',
        ),
        migrations.AddField(
            model_name='homebenner',
            name='highlightwords',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homebenner',
            name='titlesecond',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
