# Generated by Django 5.1.4 on 2025-01-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySchoolApp', '0006_rename_title_homebenner_titlefirst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebenner',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='slides/videos/'),
        ),
    ]
