# Generated by Django 5.1.4 on 2025-01-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySchoolApp', '0007_homebenner_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebenner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
